const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),d=JSON.parse(fs.readFileSync(path.join(root,'content/site.json'),'utf8')),out=path.join(root,'docs');
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const t=(zh,en)=>`<span data-lang="zh">${esc(zh)}</span><span data-lang="en" lang="en">${esc(en)}</span>`;
const text=x=>typeof x==='string'?esc(x):t(x.zh,x.en);
const safe=x=>/^(https:\/\/|mailto:|\.\/assets\/)/.test(x||'')?esc(x):'';
const arrow='<span aria-hidden="true">→</span>';
const link=(url,label,cls='')=>safe(url)?`<a class="${cls}" href="${safe(url)}" target="_blank" rel="noopener noreferrer">${text(label)} <span aria-hidden="true">↗</span></a>`:'';
const resources=x=>{const entries=Object.entries(x||{});return entries.length?`<div class="resource-links">${entries.map(([k,v])=>link(v,resourceLabels[k]||bi(k,k))).join('')}</div>`:'';};
const assetVersion=require('crypto').createHash('sha256').update(fs.readFileSync(path.join(out,'site-v2.css'))).update(fs.readFileSync(path.join(out,'site-v2.js'))).digest('hex').slice(0,10);
const pages=[['index','首页','Home'],['research','研究','Research'],['team','团队','Team'],['publications','论文','Publications'],['news','动态','News'],['join','加入我们','Join us']];
const pi=d.people[0];
const paperSort=(a,b)=>b.year-a.year || (b.conferencePriority||0)-(a.conferencePriority||0) || (b.sortOrder||0)-(a.sortOrder||0) || String(b.sortDate||'').localeCompare(String(a.sortDate||'')) || String(a.title.en||a.title).localeCompare(String(b.title.en||b.title));
// The public catalogue is reserved for published or formally accepted work.
// Keep preprints in the source JSON for provenance and later updates, but do not
// present unaccepted manuscripts as current lab output.
const papers=[...d.publications].filter(p=>p.status!=='preprint').sort(paperSort),featuredPapers=papers.filter(p=>p.core),current=d.students.filter(p=>p.current),alumni=d.students.filter(p=>!p.current);
const newsItems=[...d.news].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));
const resourceLabels={Paper:bi('论文','Paper'),PDF:bi('PDF','PDF'),Code:bi('代码','Code'),DOI:bi('DOI','DOI'),arXiv:bi('预印本','arXiv'),Source:bi('来源','Source'),'ICML poster':bi('会议页面','ICML page'),'HKUST Record':bi('学校记录','HKUST record'),'Research page':bi('研究页','Research page')};
function bi(zh,en){return {zh,en};}
function formatDate(value,locale){const m=String(value||'').match(/^(\d{4})-(\d{2})(?:-(\d{2}))?/);if(!m)return value||'';const [,year,month,day]=m;const names=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];return locale==='zh'?`${year}.${month}${day?`.${day}`:''}`:`${names[Number(month)-1]}${day?` ${Number(day)},`:''} ${year}`;}
function header(page){return `<a href="#main" class="skip-link">${t('跳到正文','Skip to content')}</a><header class="site-header"><div class="header-inner container"><a class="institution" href="https://www.hkust-gz.edu.cn/" aria-label="HKUST Guangzhou"><img src="./assets/hkust-logo-white.png" alt="The Hong Kong University of Science and Technology (Guangzhou)" width="200" height="66"></a><a class="group-identity" href="./index.html" aria-label="AIDE Lab home"><img src="./assets/aide-mark-white.svg" alt="" width="34" height="34"><span><strong>AIDE <i>Lab</i></strong><small>${t('智能 · 决策 · 经济','AI · Decisions · Economics')}</small></span></a><button type="button" id="menu-toggle" class="menu-toggle" aria-label="Navigation menu" aria-expanded="false" aria-controls="site-nav">${t('菜单','Menu')} <span aria-hidden="true">☰</span></button><nav id="site-nav" aria-label="Main navigation">${pages.map(([id,zh,en])=>`<a href="./${id}.html" ${id===page?'aria-current="page"':''}>${t(zh,en)}</a>`).join('')}</nav><button type="button" id="language-toggle" class="language-toggle" aria-label="Switch to English">EN</button></div></header>`;}
function footer(){return `<footer class="site-footer"><div class="container footer-main"><div><p class="footer-name"><img src="./assets/aide-mark.svg" alt="" width="28" height="28"> <span>AIDE <i>Lab</i></span></p><p>${text(d.brand)}</p><p>${text(d.affiliation)}</p><p>${text(d.address)}</p></div><div class="footer-links">${pages.slice(1).map(([id,zh,en])=>`<a href="./${id}.html">${t(zh,en)}</a>`).join('')}</div><div><p class="footer-label">${t('研究交流','Research enquiries')}</p><a class="footer-email" href="mailto:${esc(d.email)}">${esc(d.email)}</a><p>${link(pi.links['HKUST Profile'],'HKUST(GZ) Profile')}</p></div></div><div class="container footer-bottom"><span>© 2026 AIDE Lab</span><span>${t('张光 · 香港科技大学（广州）','Guang Zhang · HKUST(GZ)')}</span><a href="./brand.html">${t('品牌说明','Brand notes')}</a></div></footer>`;}
function pageHero(zh,en,descZh,descEn){return `<section class="page-hero"><div class="container"><div class="breadcrumb"><a href="./index.html">${t('首页','Home')}</a><span aria-hidden="true"> / </span>${t(zh,en)}</div><h1>${t(zh,en)}</h1><p>${t(descZh,descEn)}</p></div><div class="page-hero-lines" aria-hidden="true"></div></section>`;}
function heading(zh,en,href='',labelZh='',labelEn=''){return `<div class="section-heading"><h2>${t(zh,en)}</h2><span class="heading-line" aria-hidden="true"></span>${href?`<a class="section-more" href="${href}">${t(labelZh,labelEn)} ${arrow}</a>`:''}</div>`;}
function paper(p,compact=false){const title=p.title||{zh:'',en:''},venue=p.venue||{zh:'',en:''},dist=p.distinction||{zh:'',en:''};return `<article class="publication ${compact?'publication-compact':''}" id="pub-${esc(p.id)}" data-year="${p.year}" data-topic="${esc(p.topic)}" data-search="${esc([title.en,title.zh,p.authors,venue.en,venue.zh,p.year].join(' ').toLowerCase())}"><div class="pub-year">${p.year}</div><div class="pub-content">${p.figure?`<figure class="paper-figure ${compact?'paper-thumb':''}"><a class="paper-figure-link" href="${safe(p.figure.image)}" target="_blank" rel="noopener noreferrer" aria-label="${esc(title.en)} research figure"><img src="${safe(p.figure.image)}" alt="${esc(title.en)} research figure" loading="eager" decoding="async"></a><figcaption>${text(p.figure.caption)}</figcaption></figure>`:''}<div class="pub-meta"><span>${text(venue)}</span>${p.statusLabel?`<span class="paper-status">${text(p.statusLabel)}</span>`:''}${dist.en?`<span class="paper-distinction">${text(dist)}</span>`:''}</div><h3 class="paper-title-en" lang="en">${esc(title.en)}</h3><p class="authors">${esc(p.authors)}</p>${resources(p.links)}${!compact&&p.bibtex?`<details class="citation"><summary>${t('查看 BibTeX','View BibTeX')}</summary><pre>${esc(p.bibtex)}</pre><button class="copy-citation" type="button">${t('复制引用','Copy citation')}</button><span class="copy-status" role="status"></span></details>`:''}</div></article>`;}
function paperGroups(list){return [...new Set(list.map(p=>p.year))].sort((a,b)=>b-a).map(year=>`<section class="publication-year-group"><h2>${year}</h2>${list.filter(p=>p.year===year).map(p=>paper(p)).join('')}</section>`).join('');}
function paperLabel(p){const zh=(p.venue?.zh||'')+(p.distinction?.zh?' · '+p.distinction.zh:'');const en=(p.venue?.en||'')+(p.distinction?.en?' · '+p.distinction.en:'');return {zh,en};}
function feature(p){const image=p.figure?.image||p.image;const short={direct:'DiReCT',d3:'D³',prism:'PRISM',bizcompass:'BizCompass',mixing:'Data mixing'}[p.id]||p.id;return `<a class="feature-card" href="./publications.html#pub-${esc(p.id)}"><img src="${safe(image)}" alt="" width="650" height="300"><div class="feature-overlay"><span class="feature-meta">${text(paperLabel(p))}</span><h2>${esc(short)}</h2><p class="paper-title-en" lang="en">${esc(p.title.en)}</p><span class="feature-more">${t('查看论文','View paper')} ${arrow}</span></div></a>`;}
const home=`<section class="home-hero"><canvas id="network-canvas" aria-hidden="true"></canvas><div class="hero-glow" aria-hidden="true"></div><div class="container hero-content"><p class="hero-affiliation">HKUST(GZ) · FINANCIAL TECHNOLOGY</p><h1>${t('智能方法，回应真实决策。','Intelligence for real-world decisions.')}</h1><p class="hero-lead">${t('从大模型学习与推理，到智能体协作与市场行为。','From language-model learning and reasoning to agent collaboration and market behavior.')}</p><div class="hero-actions"><a href="./research.html" class="button button-gold">${t('研究方向','Explore research')} ${arrow}</a><a href="./team.html" class="hero-team-link">${t('查看团队','Meet the team')} ${arrow}</a></div></div><div class="hero-caption" aria-hidden="true">LEARNING · REASONING · DECISION MAKING</div><button type="button" id="motion-toggle" class="motion-toggle" aria-pressed="false">${t('暂停动态','Pause motion')}</button></section><div class="container featured-row">${featuredPapers.slice(0,3).map(feature).join('')}</div>
<section class="section research-overview soft-section"><div class="container">${heading('研究方向','Research Areas','./research.html','查看全部','View all')}<p class="section-intro">${text(d.intro)}</p><div class="theme-grid">${d.research.map((r,i)=>`<article class="theme-card"><span class="theme-number">0${i+1}</span><h3>${text(r.title)}</h3><p>${text(r.description)}</p><a href="./research.html#${esc(r.id)}">${t('了解更多','Learn more')} ${arrow}</a></article>`).join('')}</div></div></section>
<section class="section"><div class="container home-two-columns"><div>${heading('精选成果','Selected Work','./publications.html','查看全部论文','View all publications')}${featuredPapers.slice(0,4).map(p=>paper(p,true)).join('')}</div><aside class="news-aside"><h2>${t('动态','News')}</h2>${newsItems.slice(0,4).map(n=>`<article><span class="news-icon" aria-hidden="true">${esc(n.icon||'•')}</span><time datetime="${esc(n.date)}"><span data-lang="zh">${esc(formatDate(n.date,'zh'))}</span><span data-lang="en">${esc(formatDate(n.date,'en'))}</span></time><p>${text(n.text)}</p><a class="news-arrow" href="${safe(n.url)}" target="_blank" rel="noopener noreferrer" aria-label="View research">↗</a></article>`).join('')}<a href="./news.html" class="more-news">${t('查看全部动态','View all news')} ${arrow}</a></aside></div></section>
<section class="team-banner"><div class="container"><p class="eyebrow-light">HKUST(GZ) · GUANGZHOU</p><h2>${t('每个项目，都从一个问题开始。','Every project starts with a question.')}</h2><p>${t('我们在模型、智能体与金融市场之间寻找可验证的答案。','We look for testable answers across models, agents, and financial markets.')}</p><div class="team-stats"><div><strong>7</strong><span>${t('在读博士生','Doctoral students')}</span></div><div><strong>1</strong><span>${t('在读硕士生','Master’s student')}</span></div><div><strong>3</strong><span>${t('研究方向','Research areas')}</span></div></div><a href="./team.html" class="button button-white">${t('查看团队','Meet the team')} ${arrow}</a></div></section>
<section class="section soft-section"><div class="container">${heading('实验室负责人','Principal Investigator')}<div class="pi-home"><a href="./team.html#principal-investigator"><img src="${safe(pi.photo)}" alt="Guang Zhang" width="260" height="320" loading="eager" decoding="async"></a><div><h3>${text(pi.name)}</h3><p class="pi-role">${text(pi.role)}</p><p>${text(pi.bio)}</p>${resources(pi.links)}<a class="button button-blue" href="./join.html">${t('联系张光','Contact Guang Zhang')} ${arrow}</a></div></div></div></section>`;
const research=pageHero('研究','Research','我们关心智能方法如何改变研究、决策与市场。','We study how intelligent methods reshape research, decisions, and markets.')+`<div class="container subnav">${d.research.map(r=>`<a href="#${esc(r.id)}">${text(r.title)}</a>`).join('')}</div><section class="section"><div class="container">${d.research.map((r,i)=>`<article id="${esc(r.id)}" class="research-area"><div class="area-label">0${i+1}</div><div><h2>${text(r.title)}</h2><p>${text(r.description)}</p><div class="tags">${r.tags.map(x=>`<span>${text(x)}</span>`).join('')}</div><div class="related-papers">${papers.filter(p=>p.topic===r.id).slice(0,3).map(p=>`<a href="./publications.html?q=${encodeURIComponent(p.title.en)}"><span class="paper-title-en" lang="en">${esc(p.title.en)}</span> ${arrow}</a>`).join('')}</div></div></article>`).join('')}</div></section><section class="section soft-section"><div class="container">${heading('研究项目','Research Projects')}<div class="project-grid">${d.projects.map(p=>`<article class="project" id="${esc(p.id)}">${p.image?`<a class="project-image" href="${safe(Object.values(p.links)[0])}" target="_blank" rel="noopener noreferrer"><img src="${safe(p.researchImage||p.image)}" alt="${esc(p.title.en)} — research figure" loading="eager" decoding="async" width="1000" height="480"></a>`:'<div class="project-type">FINANCE & LANGUAGE MODELS</div>'}<div class="project-copy"><p class="project-meta">${text(p.label)}</p><h3>${text(p.title)}</h3><p>${text(p.summary)}</p>${resources(p.links)}</div></article>`).join('')}</div></div></section>`;
function student(p){const index=Math.max(0,current.indexOf(p));const portrait=p.portrait||`./assets/minion-${(index%8)+1}.webp`;const paperIds=[...new Set([...(p.paperIds||[]),...papers.filter(pub=>pub.authors&&pub.authors.split(', ').includes(p.name)).map(pub=>pub.id)])];return `<article class="student-card"><img class="student-portrait" src="${safe(portrait)}" alt="${esc(p.name)} temporary portrait placeholder" width="96" height="96" loading="eager" decoding="async"><div><h4>${esc(p.name)}</h4><p>${esc(p.years)} · ${p.supervision==='Co'?t('联合指导','Co-supervised'):t('主要指导','Primary supervision')}</p>${resources(p.links)}${paperIds.length?`<a class="student-papers" href="./publications.html?author=${encodeURIComponent(p.name)}">${t('相关论文','Publications')} (${paperIds.length}) ${arrow}</a>`:''}</div></article>`;}
const team=pageHero('团队','Our Team','一起提出问题、验证想法，并把研究做得更好。','People who ask better questions, test ideas, and build together.')+`<section class="section"><div class="container team-layout"><aside class="pi-sidebar" id="principal-investigator"><img src="${safe(pi.photo)}" alt="Guang Zhang" width="210" height="250"><h2>${text(pi.name)}</h2><p class="pi-role">${text(pi.role)}</p><p>${text(d.affiliation)}</p><dl><dt>${t('邮箱','Email')}</dt><dd><a href="mailto:${esc(d.email)}">${esc(d.email)}</a></dd><dt>${t('办公室','Office')}</dt><dd>W1 L5 509</dd></dl>${resources(pi.links)}<div class="sidebar-links"><a href="#current-students">${t('当前成员','Current members')}</a><a href="#alumni">${t('毕业生与培养记录','Graduates & degree records')}</a></div></aside><div class="team-main"><div class="team-intro"><h2>${t('实验室负责人','Principal Investigator')}</h2><p>${text(pi.bio)}</p></div><section id="current-students"><h2 class="ruled-heading">${t('当前成员','Current Members')}</h2>${['PhD','Master'].map(degree=>`<h3 class="group-heading">${degree==='PhD'?t('博士生','Doctoral students'):t('硕士生','Master’s students')}</h3><div class="student-grid">${current.filter(p=>p.degree===degree).map(student).join('')}</div>`).join('')}</section><section id="alumni" class="alumni-section"><h2 class="ruled-heading">${t('毕业生与培养记录','Graduates & Completed Degrees')}</h2><p class="record-note">${t('校友按已完成学位列出；仍在本组继续攻读博士的成员同时列于当前成员。','Alumni are listed by completed degree; members who continue into doctoral study remain listed above.')}</p>${['PhD','Master'].map(degree=>`<h3 class="group-heading">${degree==='PhD'?t('博士毕业生','Doctoral graduates'):t('硕士毕业生','Master’s graduates')}</h3><div class="alumni-list">${alumni.filter(p=>p.degree===degree).map(p=>`<article class="alumnus"><div><h4>${esc(p.name)}</h4><p>${esc(p.years)} · ${p.supervision==='Co'?t('联合指导','Co-supervised'):t('主要指导','Primary supervision')}</p></div><p class="placement">${text(p.placement)}</p></article>`).join('')}</div>`).join('')}</section></div></div></section>`;
const publications=pageHero('论文与成果','Publications','从金融计量到大模型与智能体的研究成果。','Work across financial econometrics, language models, and agents.')+`<section class="section"><div class="container publications-layout"><aside class="publication-sidebar"><h2>${t('按年份浏览','Browse by year')}</h2><div class="year-links"><button type="button" data-filter-year="" aria-pressed="true">${t('全部年份','All years')} <span>${papers.length}</span></button>${[...new Set(papers.map(p=>p.year))].map(y=>`<button type="button" data-filter-year="${y}" aria-pressed="false">${y} <span>${papers.filter(p=>p.year===y).length}</span></button>`).join('')}</div><a class="bib-download" href="./publications.bib" download>${t('下载全部 BibTeX','Download all BibTeX')} ↓</a></aside><div class="publication-main"><div class="publication-tools"><label class="search-label" for="publication-search">${t('搜索标题、作者或会议','Search title, author, or venue')}<input type="search" id="publication-search" autocomplete="off"></label><label for="publication-topic">${t('研究方向','Research area')}<select id="publication-topic"><option value="" data-option-zh="全部方向" data-option-en="All areas">全部方向</option><option value="models" data-option-zh="学习与推理" data-option-en="Learning & reasoning">学习与推理</option><option value="agents" data-option-zh="智能体与决策" data-option-en="Agents & decisions">智能体与决策</option><option value="markets" data-option-zh="金融与计量" data-option-en="Markets & models">金融与计量</option></select></label><button type="button" id="clear-filters">${t('重置','Reset')}</button></div><p id="publication-count" role="status" aria-live="polite">${t(`共 ${papers.length} 篇成果`,`${papers.length} research records`)}</p><div class="publications-list">${paperGroups(papers)}</div><p id="no-publications" hidden>${t('没有匹配的论文，请调整筛选条件。','No publications match. Try changing your filters.')}</p></div></div></section>`;
const news=pageHero('最新动态','News','论文发表、研究进展与团队动态。','Papers, research milestones, and lab news.')+`<section class="section"><div class="container news-page">${[...new Set(newsItems.map(n=>n.date.slice(0,4)))].map(y=>`<section class="news-year"><h2>${y}</h2><div>${newsItems.filter(n=>n.date.startsWith(y)).map(n=>`<article class="news-item"><span class="news-icon" aria-hidden="true">${esc(n.icon||'•')}</span><time datetime="${esc(n.date)}"><span data-lang="zh">${esc(formatDate(n.date,'zh'))}</span><span data-lang="en">${esc(formatDate(n.date,'en'))}</span></time><div><p>${text(n.text)}</p><a href="${safe(n.url)}" target="_blank" rel="noopener noreferrer">${t('查看成果','View research')} ${arrow}</a></div></article>`).join('')}</div></section>`).join('')}</div></section>`;
const join=pageHero('加入我们','Join us','围绕共同的问题展开交流。','Talk with us about questions we share.')+`<section class="section"><div class="container join-layout"><div><h2>${t('研究交流','Research enquiries')}</h2><p>${text(d.recruitment)}</p><div class="contact-details"><span>${t('负责人','Principal investigator')}</span><strong>${text(pi.name)}</strong><span>${t('研究交流','Research enquiries')}</span><a href="mailto:${esc(d.email)}">${esc(d.email)}</a><span>${t('办公室','Office')}</span><p>${text(d.address)}</p></div><a class="button button-blue" href="mailto:${esc(d.email)}">${t('发送邮件','Email us')} ${arrow}</a></div><div class="join-information"><h2>${t('想一起研究？','Interested in working together?')}</h2><p>${t('请在来信中说明你的研究方向、经历，以及希望继续追问的问题；如有代表作或项目链接，也欢迎一并附上。','Tell us about your research interests, experience, and the questions you would like to pursue. Links to representative work or projects are welcome.')}</p><ul>${d.research.map(r=>`<li>${text(r.title)}</li>`).join('')}</ul><p class="record-note">${t('招生与招聘信息以学校和负责人后续发布为准。','Admissions and openings follow later announcements from the university and the PI.')}</p>${link('https://www.hkust-gz.edu.cn/','HKUST(GZ) website','university-link')}</div></div></section><figure class="campus-photo"><img src="./assets/campus.webp" alt="HKUST Guangzhou campus" width="2200" height="1648" loading="eager" decoding="async"><figcaption>${t('香港科技大学（广州）校园 · 图片来源：学校官网','HKUST(GZ) campus · Photograph from the university website')}</figcaption></figure>`;
const bodies={index:home,research,team,publications,news,join};fs.mkdirSync(out,{recursive:true});
for(const [id,zh,en] of pages){fs.writeFileSync(path.join(out,id+'.html'),`<!doctype html><html lang="zh-CN" data-locale="zh"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#031b3b"><title>${esc(zh)} · ${esc(d.name.zh)}</title><meta name="description" content="AIDE Lab at HKUST(GZ): language models, agents, finance, and economic decision-making."><link rel="icon" href="./assets/favicon.svg"><link rel="stylesheet" href="./assets/fonts.css"><link rel="stylesheet" href="./site-v2.css?v=${assetVersion}"><script>try{if(localStorage.getItem('lab-locale')==='en'){document.documentElement.dataset.locale='en';document.documentElement.lang='en'}}catch{}</script><script defer src="./site-v2.js?v=${assetVersion}"></script></head><body data-page="${id}" data-title-zh="${esc(zh)}" data-title-en="${esc(en)}">${header(id)}<main id="main">${bodies[id]}</main>${footer()}<noscript><p class="noscript-note">中文静态内容可直接阅读。Enable JavaScript for language switching and filters.</p></noscript></body></html>`);}
fs.writeFileSync(path.join(out,'publications.bib'),papers.map(p=>p.bibtex||'').filter(Boolean).join('\n\n'));
fs.writeFileSync(path.join(out,'robots.txt'),'User-agent: *\nDisallow: /\n');
console.log('Built six independent pages, shared navigation, and downloadable BibTeX.');
