const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..'),d=JSON.parse(fs.readFileSync(path.join(root,'content/site.json'),'utf8'));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const t=(zh,en)=>`<span data-lang="zh">${esc(zh)}</span><span data-lang="en" lang="en">${esc(en)}</span>`;
const text=x=>typeof x==='string'?esc(x):t(x.zh,x.en);
const url=x=>typeof x==='string'&&/^(https:\/\/|mailto:|\.\/assets\/)/.test(x)?esc(x):'';
const link=(href,label)=>url(href)?`<a href="${url(href)}" ${href.startsWith('https:')?'target="_blank" rel="noopener noreferrer"':''}>${esc(label)} <span aria-hidden="true">↗</span></a>`:'';
function art(kind){
 if(kind==='network')return '<svg viewBox="0 0 400 200" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width="1"><path d="M60 100L140 45 210 120 310 60 345 145 210 120 140 160 60 100 210 120 140 45 310 60"/><path d="M140 160L310 60M60 100L345 145" opacity=".35"/></g><g fill="currentColor">'+[[60,100],[140,45],[210,120],[310,60],[345,145],[140,160]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="6"/>`).join('')+'</g></svg>';
 if(kind==='circles')return '<svg viewBox="0 0 400 200" aria-hidden="true"><g fill="none" stroke="currentColor">'+[0,12,24,36].map(x=>`<circle cx="165" cy="100" r="${70-x}"/><circle cx="235" cy="100" r="${70-x}"/>`).join('')+'</g><circle cx="200" cy="100" r="5" fill="currentColor"/></svg>';
 return '<svg viewBox="0 0 400 200" aria-hidden="true"><g fill="none" stroke="currentColor">'+Array.from({length:8},(_,i)=>`<path d="M30 ${50+i*14}C110 ${-35+i*18} 180 ${235-i*6} 370 ${45+i*14}"/>`).join('')+'</g></svg>';
}
const mark='<span class="mark" aria-hidden="true"><i></i><i></i><i></i><i></i></span>';
const nav=[['research','研究','Research'],['projects','项目','Projects'],['publications','论文','Publications'],['people','团队','People']];
const pubHtml=d.publications.length?`<div class="publication-tools"><label>${t('搜索论文','Search publications')}<input id="publication-search" type="search" autocomplete="off"></label><label>${t('年份','Year')}<select id="publication-year"><option value="" data-option-zh="全部" data-option-en="All">全部</option>${[...new Set(d.publications.map(p=>p.year))].sort((a,b)=>b-a).map(y=>`<option>${esc(y)}</option>`).join('')}</select></label><label>${t('研究方向','Topic')}<select id="publication-topic"><option value="" data-option-zh="全部方向" data-option-en="All topics">全部方向</option><option value="models" data-option-zh="学习与推理" data-option-en="Learning & reasoning">学习与推理</option><option value="agents" data-option-zh="智能体与决策" data-option-en="Agents & decisions">智能体与决策</option><option value="markets" data-option-zh="金融与计量" data-option-en="Finance & econometrics">金融与计量</option></select></label></div><div class="publications-list">${[...d.publications].sort((a,b)=>b.year-a.year).map(p=>`<article class="publication" id="pub-${esc(p.id)}" data-topic="${esc(p.topic||'markets')}" data-year="${esc(p.year)}" data-search="${esc([p.title,p.authors,p.venue,p.year].join(' ').toLowerCase())}"><div class="pub-year">${esc(p.year)}</div><div><p class="eyebrow">${esc(p.venue)}</p><h3>${esc(p.title)}</h3><p>${esc(p.authors)}</p>${p.note?`<p class="publication-note">${text(p.note)}</p>`:''}<div class="resource-links">${Object.entries(p.links||{}).map(([k,v])=>link(v,k)).join('')}</div>${p.bibtex?`<details><summary>BibTeX</summary><pre>${esc(p.bibtex)}</pre></details>`:''}</div></article>`).join('')}</div><p id="publication-count" role="status" aria-live="polite"></p>`:`<div class="empty-publications"><span class="large-serif">Aa.</span><div><h3>${t('每一项成果，都有迹可循。','Research, with a traceable record.')}</h3><p>${t('论文信息整理中。这里将展示标题、作者、年份与会议，并连接论文、代码、数据和引用。','Publications are being prepared. Each entry will connect the title, authors, venue, and year with papers, code, data, and citations.')}</p><span class="status-label">${t('尚未添加论文','No publications added yet')}</span></div></div>`;
const supervision=x=>x==='Co'?t('联合指导','Co-supervised'):t('主要指导','Primary supervision');
const studentCard=p=>`<article class="student-card"><div class="student-top"><span class="initials" aria-hidden="true">${esc(p.name.split(' ').map(x=>x[0]).join(''))}</span><span class="student-years">${esc(p.years)}</span></div><h3>${esc(p.name)}</h3><p>${supervision(p.supervision)}</p><div class="resource-links">${Object.entries(p.links||{}).map(([k,v])=>link(v,k)).join('')}${p.paperIds?.length?`<a href="#publications" data-author="${esc(p.name)}">${t('相关论文','Publications')} (${p.paperIds.length}) →</a>`:''}</div></article>`;
const students=d.students||[];
const studentHtml=['PhD','Master'].map(degree=>{const people=students.filter(p=>p.current&&p.degree===degree);return people.length?`<div class="student-group"><h3 class="group-title">${degree==='PhD'?t('博士生','Doctoral students'):t('硕士生','Master’s students')} <span>${people.length}</span></h3><div class="student-grid">${people.map(studentCard).join('')}</div></div>`:'';}).join('');
const alumniHtml=`<details class="alumni"><summary>${t('毕业生与培养记录','Graduates & completed degrees')} <span>${students.filter(p=>!p.current).length}</span></summary><p class="alumni-note">${t('按已完成学位列示；其中 Jiaxin Liu、Junying Ma 现继续攻读博士。','Listed by completed degree; Jiaxin Liu and Junying Ma are also current doctoral students.')}</p>${['PhD','Master'].map(degree=>`<h3 class="group-title">${degree==='PhD'?t('博士毕业生','Doctoral graduates'):t('硕士毕业生','Master’s graduates')}</h3><div class="alumni-grid">${students.filter(p=>!p.current&&p.degree===degree).map(p=>`<article class="alumnus"><h4>${esc(p.name)}</h4><p>${esc(p.years)} · ${supervision(p.supervision)}</p>${p.placement?`<p class="placement">${esc(p.placement)}</p>`:''}</article>`).join('')}</div>`).join('')}</details>`;
const page=`<!doctype html>
<html lang="zh-CN" data-locale="zh"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(d.name.zh)} · ${d.preview?'设计预览':'Research Lab'}</title><meta name="description" content="${esc(d.name.zh)} — ${esc(d.affiliation.zh)}。研究、项目、论文与团队。">${d.preview?'<meta name="robots" content="noindex,nofollow">':''}<meta name="theme-color" content="#f6f5f0"><link rel="icon" href="./assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="./style.css"><script defer src="./app.js"></script></head><body>
<a class="skip-link" href="#main">${t('跳至正文','Skip to content')}</a>
${d.preview?`<div class="preview-bar"><div class="container"><span><b>DESIGN PREVIEW</b> ${t('主页预览 · 实验室正式名称筹备中','Website preview · formal lab name in preparation')}</span><a href="./references.html">${t('查看调研与素材清单','References & content checklist')} <span aria-hidden="true">↗</span></a></div></div>`:''}
<header class="site-header"><div class="container header-inner"><a class="brand" href="#" aria-label="${esc(d.name.zh)}">${mark}<span><strong>${esc(d.shortName)}<span class="brand-dot">.</span></strong><small>${text(d.name)}</small></span></a><button id="menu-toggle" class="menu-toggle" type="button" aria-expanded="false" aria-controls="site-nav">${t('菜单','Menu')} ☰</button><nav id="site-nav" aria-label="Main navigation">${nav.map(([id,zh,en])=>`<a href="#${id}">${t(zh,en)}</a>`).join('')}<a class="join-link" href="#join">${t('加入我们','Join us')} <span aria-hidden="true">↗</span></a></nav><button class="language-toggle" id="language-toggle" aria-label="Switch to English" type="button">EN <span aria-hidden="true">↔</span></button></div></header>
<main id="main"><section class="hero container" aria-labelledby="hero-title"><div class="hero-copy"><p class="eyebrow"><span class="live-dot"></span> LEARNING · AGENTS · FINANCE</p><h1 id="hero-title">${['zh','en'].map(l=>`<span data-lang="${l}">${d.hero[l].split(/(<br>|<span>|<\/span>)/).map(s=>['<br>','<span>','</span>'].includes(s)?s:esc(s)).join('')}</span>`).join('')}</h1><p class="hero-intro">${text(d.intro)}</p><div class="hero-actions"><a class="button primary" href="#research">${t('探索研究','Explore our research')} <span aria-hidden="true">↗</span></a><a class="text-link" href="#people">${t('认识团队','Meet the people')} <span aria-hidden="true">→</span></a></div><div class="affiliation">${text(d.affiliation)}</div></div><div class="hero-figure"><div class="figure-top"><span>FIG. 01 / CONNECTED INTELLIGENCE</span><span>+ + +</span></div><svg class="orb" viewBox="0 0 560 500" role="img" aria-label="Abstract illustration of connected research ideas"><defs><radialGradient id="glow"><stop stop-color="#ebe3d6"/><stop offset="1" stop-color="#f6f5f0" stop-opacity="0"/></radialGradient><pattern id="dots" width="24" height="24" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".8" fill="#c4c3bb"/></pattern></defs><rect width="560" height="500" fill="url(#dots)"/><circle cx="280" cy="245" r="220" fill="url(#glow)"/><g class="orbit-lines" fill="none" stroke="#6d7778" stroke-width=".8"><circle cx="280" cy="245" r="162"/>${[25,50,80,115,145].map(a=>`<ellipse cx="280" cy="245" rx="162" ry="63" transform="rotate(${a} 280 245)"/>`).join('')}<ellipse cx="280" cy="245" rx="205" ry="103" transform="rotate(-24 280 245)" stroke="#b26850" stroke-width="1.4"/></g><g fill="#1f3b3a"><circle cx="180" cy="118" r="9"/><circle cx="379" cy="117" r="5"/><circle cx="440" cy="263" r="7"/><circle cx="167" cy="360" r="5"/></g><circle cx="280" cy="245" r="15" fill="#bc694d"/><circle cx="280" cy="245" r="26" stroke="#bc694d" fill="none" opacity=".4"/><path d="M280 245L434 386H512M180 118L122 54H38" fill="none" stroke="#828c87"/><g fill="#586a65" font-size="10" font-family="monospace"><text x="38" y="45">DATA</text><text x="446" y="405">MODELS</text><text x="258" y="457">RESEARCH IN MOTION</text></g></svg><div class="figure-bottom"><span>${t('在学习、决策与金融之间建立连接。','Connecting learning, decisions, and finance.')}</span><span>↗</span></div></div></section>
<section class="news-strip container" aria-labelledby="news-title"><h2 id="news-title"><span class="live-dot"></span>${t('最新动态','Latest news')}</h2><div>${d.news.length?d.news.slice(0,3).map(n=>`<article><time datetime="${esc(n.date)}">${esc(n.date)}</time><p>${text(n.text)} ${n.url?link(n.url,'↗'):''}</p></article>`).join(''):`<article><span class="news-label">${t('内容筹备中','IN PREPARATION')}</span><p>${t('论文发表、项目进展与团队故事，将在这里持续更新。','Publications, project milestones, and stories from the lab will appear here.')}</p></article>`}</div></section>
<section class="section container" id="research"><div class="section-heading"><div><p class="eyebrow">01 / RESEARCH</p><h2>${t('围绕重要的问题。','Questions worth pursuing.')}</h2></div><p>${t('从模型的能力，到现实中的问题。','From model capabilities to real-world questions.')}</p></div><div class="research-grid">${d.research.map(r=>`<article class="research-card"><div class="card-top"><span>${r.label}</span><span>RESEARCH THEME</span></div><div class="research-art ${r.visual}">${art(r.visual)}</div><h3>${text(r.title)}</h3><p>${text(r.description)}</p><div class="tags">${r.tags.map(x=>`<span>${esc(x)}</span>`).join('')}</div></article>`).join('')}</div></section>
<section class="section projects-section" id="projects"><div class="container"><div class="section-heading"><div><p class="eyebrow">02 / SELECTED WORK</p><h2>${t('让想法，成为可见的探索。','Ideas, made tangible.')}</h2></div><p>${t('以代表项目连接科学问题、<br>技术方法与研究成果。'.replace('<br>',''),'Connect scientific questions, methods, and findings through selected projects.')}</p></div>${d.projects.length?d.projects.map(p=>`<article class="featured-project"><div class="project-art">${p.image?`<img src="${url(p.image)}" alt="${esc(p.title.zh)}" loading="lazy">`:art('network')}</div><div class="project-copy"><p class="eyebrow">${esc(p.label||"SELECTED PROJECT")}</p><h3>${text(p.title)}</h3><p>${text(p.summary)}</p><div class="resource-links">${Object.entries(p.links||{}).map(([k,v])=>link(v,k)).join('')}</div></div></article>`).join(''):`<article class="featured-project"><div class="project-art">${art('network')}<span class="art-caption">QUESTION → METHOD → DISCOVERY</span></div><div class="project-copy"><p class="eyebrow">${t('精选项目 · 内容待补充','SELECTED PROJECT · CONTENT PENDING')}</p><h3>${t('从一个问题，<br>到一项研究。'.replace('<br>',''),'From a question to a research project.')}</h3><p>${t('为每个代表项目准备一张清晰的研究图、一段易懂的介绍，以及论文、代码或演示链接。','A clear research figure, a short explanation, and links to a paper, code, or demonstration will bring each project to life.')}</p><span class="status-label">${t('项目资料准备中','Project materials in preparation')}</span></div></article>`}</div></section>
<section class="section container" id="publications"><div class="section-heading"><div><p class="eyebrow">03 / PUBLICATIONS</p><h2>${t('研究成果。','Published work.')}</h2></div><p>${t('论文、预印本与开放研究资源。','Papers, preprints, and open research resources.')}</p></div>${pubHtml}</section>
<section class="section people-section" id="people"><div class="container"><div class="section-heading"><div><p class="eyebrow">04 / PEOPLE</p><h2>${t('研究背后，是人。','People behind the questions.')}</h2></div><p>${t('不同的视角，让探索更加丰富。','Different perspectives make discovery possible.')}</p></div><div class="people-grid ${d.people.length===1?'single-pi':''}">${d.people.length?d.people.map(p=>`<article class="person"><div class="portrait">${p.photo?`<img src="${url(p.photo)}" alt="${esc(p.name.zh)}" loading="lazy">`:'<span class="portrait-symbol" aria-hidden="true"></span>'}</div><div class="person-bio"><p class="eyebrow">PRINCIPAL INVESTIGATOR</p><h3>${text(p.name)}</h3><p>${text(p.role)}</p>${p.bio?`<p class="bio-text">${text(p.bio)}</p>`:''}<div class="resource-links">${Object.entries(p.links||{}).map(([k,v])=>link(v,k)).join('')}</div></div></article>`).join(''):[['负责人','Principal investigator'],['博士后与研究人员','Postdocs & researchers'],['学生成员','Students']].map(([zh,en],i)=>`<article class="person placeholder-person"><div class="portrait portrait-${i}"><span class="portrait-symbol" aria-hidden="true"><i></i></span><span class="portrait-note">${t('照片待提供','PHOTO TO COME')}</span></div><h3>${t(zh,en)}</h3><p>${t('姓名与个人介绍待补充','Name and biography to be added')}</p></article>`).join('')}</div>${studentHtml}${alumniHtml}<p class="team-pending">${t('学生与校友信息根据团队提供的培养名单整理。','Student and alumni records are based on the roster provided by the group.')}</p></div></section>
<section class="join-section container" id="join"><div><p class="eyebrow">05 / JOIN & CONNECT</p><h2>${t('下一个问题，<br>期待一起探索。'.replace('<br>',''),'The next question starts with us.')}</h2></div><div><p>${text(d.recruitment)}</p>${d.email?`<a class="button primary" href="mailto:${esc(d.email)}">${t('联系实验室','Contact the lab')} ↗</a>`:`<span class="contact-pending">${t('联系邮箱待确认','Contact email to be confirmed')}</span>`}<p class="address">${text(d.address)}</p></div></section></main>
<footer class="footer"><div class="container"><a href="#" class="footer-brand">${mark} ${esc(d.shortName)}.</a><span>${text(d.name)} · ${text(d.affiliation)}</span><a href="#">${t('回到顶部','Back to top')} ↑</a></div></footer><noscript><div class="noscript-note">当前展示中文内容；开启 JavaScript 可切换英文。The Chinese version is shown. Enable JavaScript to switch to English.</div></noscript></body></html>`;
fs.mkdirSync(path.join(root,'docs'),{recursive:true});fs.writeFileSync(path.join(root,'docs/index.html'),page);
fs.writeFileSync(path.join(root,'docs/robots.txt'),d.preview?'User-agent: *\nDisallow: /\n':'User-agent: *\nAllow: /\n');
console.log('Built docs/index.html from content/site.json');
